name: login
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  barcode_scan: "^0.0.4"
  device_info: "^0.2.1"
  geoip: "^1.0.1"





dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/users.png
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf
plugin:
    androidPackage: com.apptreesoftware.barcodescan
    pluginClass: BarcodeScanPlugin
    
